---
- semaphore:
    name: identity-infrastructure-make
    max: 1

- job:
    name: golang-make-functional-identity
    parent: golang-make-functional
    description: |
      A job deploying OpenStack identity on a OTC VM for Go functional tests
    vars:
      provider: "otc"
      vm_name: "keystone-go-make"
      seed: "-go-make"
      repo_tmp: "/tmp/identity-deploy"
      result_clouds: "/tmp/clouds.yaml"
      make_env:
        OS_CLOUD: "default"
        OS_CLIENT_CONFIG_FILE: "{{ result_clouds }}"
    semaphores: identity-infrastructure-make
    pre-run:
      - ci/playbooks/pre.yaml
    cleanup-run:
      - ci/playbooks/post.yaml

- semaphore:
    name: identity-infrastructure-tox
    max: 1

- job:
    name: tox-functional-identity
    parent: tox-functional
    description: |
      A job deploying OpenStack identity on a OTC VM for tox functional tests
    vars:
      provider: "otc"
      vm_name: "keystone-tox"
      seed: "-tox"
      repo_tmp: "/tmp/identity-deploy"
      result_clouds: "/tmp/clouds.yaml"
      tox_environment:
        OS_CLOUD: "default"
        OS_CLIENT_CONFIG_FILE: "{{ result_clouds }}"
    semaphores: identity-infrastructure-tox
    pre-run:
      - ci/playbooks/pre.yaml
    cleanup-run:
      - ci/playbooks/post.yaml

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - otc-tox-linters
    check-post:
      jobs:
        - tox-functional-identity
        - golang-make-functional-identity
    gate:
      jobs:
        - otc-tox-linters
        - tox-functional-identity
        - golang-make-functional-identity
