---
- name: "Run ansible from ansible"
  hosts: all
  tasks:
    - name: "Run destroy playbook"
      args:
        chdir: "{{ zuul.project.src_dir }}"
      shell: >
        ansible-playbook
        -e "provider='{{ provider }}' vm_name='{{ vm_name }}' seed='{{seed}}'"
        playbooks/destroy.yaml
