---
- name: "Run ansible from ansible"
  hosts: all
  tasks:
    - name: "Install ansible"
      pip:
        name: ansible
        version: "5.1.0"
        state: present
    - name: "Install requirements"
      args:
        chdir: "{{ zuul.project.src_dir }}"
      shell: >
        ansible-galaxy
        install
        -r requirements.yaml
    - name: "Run create playbook"
      args:
        chdir: "{{ zuul.project.src_dir }}"
      shell: >
        ansible-playbook
        -e "provider='{{ provider }}' vm_name='{{ vm_name }}' seed='{{seed}}'"
        playbooks/create.yaml
