---
otc_build_dir: build

_release_version_map:
  bionic: "18.04"
  focal: "20.04"

otc_server_name:
otc_public_key:
otc_dns_nameservers:
  - "100.125.4.25"
  - "100.125.129.199"
otc_cidr: "192.168.0.0/16"
otc_flavor: "c4.4xlarge.2"
otc_ubuntu_release: "bionic"
otc_keypair_name: "keystone-kp"
otc_network_name: "keystone-nw"
otc_subnet_name: "keystone-subnet"
otc_router_name: "keystone-router"
otc_sg_name: "keystone-sg"
state: present

_tf_var_file: "{{ playbook_dir }}/{{ otc_build_dir }}/input.tfvar"
