- vars:
    release_version: "{{ _release_version_map[otc_ubuntu_release] }}"
  set_fact:
    otc_image: "Standard_Ubuntu_{{ release_version }}_latest" 

- name: "Create keypair"
  openstack.cloud.keypair:
    name: "{{ otc_keypair_name }}"
    public_key: "{{ otc_public_key }}"
  register: _keypair

- name: "Create VPC"
  opentelekomcloud.cloud.vpc:
    name: "{{ otc_vpc_name }}"
    cidr: "{{ otc_cidr }}"
  register: _vpc

- name: "Create subnet"
  opentelekomcloud.cloud.subnet:
    vpc_id: "{{ _vpc.vpc.id }}"
    name: "{{ otc_subnet_name }}"
    cidr: "{{ otc_cidr }}"
    gateway_ip: "{{ otc_gateway_ip }}"
    dns_list: "{{ otc_dns_nameservers }}"
  register: _subnet

- name: "Create security group"
  openstack.cloud.security_group:
    name: "{{ otc_sg_name }}"

- name: "Add inbound security group rules"
  openstack.cloud.security_group_rule:
    security_group: "{{ otc_sg_name }}"
    ethertype: IPv4
    protocol: tcp
    direction: ingress
    remote_ip_prefix: "0.0.0.0/0"
    port_range_min: "{{ item }}"
    port_range_max: "{{ item }}"
  loop: "{{ otc_allowed_ports }}"

- name: "Add outgoing security group rules"
  openstack.cloud.security_group_rule:
    security_group: "{{ otc_sg_name }}"
    ethertype: IPv4
    direction: egress
    remote_ip_prefix: "0.0.0.0/0"

- name: "Create required volume"
  openstack.cloud.volume:
    display_name: "v-{{ otc_server_name }}"
    image: "{{ otc_image }}"
    size: 20
    volume_type: SSD
    bootable: yes
  register: _volume

- name: "Create server"
  openstack.cloud.server:
    name: "{{ otc_server_name }}"
    boot_volume: "{{ _volume.volume.id }}"
    security_groups:
      - "{{ otc_sg_name }}"
    flavor: "{{ otc_flavor }}"
    key_name: "{{ otc_keypair_name }}"
    network: "{{ _subnet.subnet.neutron_network_id }}"
    terminate_volume: true

- name: "Create floating IP"
  openstack.cloud.floating_ip:
    server: "{{ otc_server_name }}"
    network: "admin_external_net"
  register: _floating_ip

- name: Save floating IP
  set_fact:
    otc_floating_ip: "{{ _floating_ip.floating_ip.floating_ip_address }}"
