---
- name: "Setup VM"
  hosts: host
  roles:
    - multipass_vm
  tasks:
    - name: "Set guest address"
      add_host:
        name: guest
        groups:
          - keystone_all
        ansible_host: "{{ vm_address }}"
        ansible_user: keystone
        ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ vm_private_key }}"
        db_pwd: "Spacibo2022"
      changed_when: no

- name: "Install RabbitMQ"
  hosts: guest
  become: yes
  vars:
    erlang_series: 24
    rabbitmq_version: 3.9.11
  roles:
    - rockandska.erlang
    - geerlingguy.rabbitmq

- name: "Prepare to install"
  hosts: guest
  become: yes
  tasks:
    - name: "Uninstall not needed packages"
      apt:
        pkg:
          - python3-yaml
        state: absent
        autoremove: yes
    - name: "Install packages"
      apt:
        pkg:
          - python3-pip
          - mysql-server
        update_cache: yes
        cache_valid_time: 1200
    - name: "Upgrade PIP"
      pip:
        name:
          - pip
        state: latest
    - name: "Install PIP packages"
      pip:
        name:
          - openstacksdk
          - virtualenv
          - pymysql
    - name: "Create cgi-bin"
      file:
        path: "/var/www/cgi-bin/keystone"
        state: directory
    - name: "Create /etc/keystone"
      file:
        path: "/etc/keystone"
        state: directory
    - name: "Prepare keystone key pair"
      community.crypto.openssh_keypair:
        path: "/home/keystone/.ssh/id_rsa"
        type: "rsa"
    - name: "Create .my.cnf"
      copy:
        src: .my.cnf
        dest: "{{ item }}/.my.cnf"
      loop:
        - "/root"
        - "/home/keystone"
    - name: "Create openstack config dir"
      file:
        path: "~/.config/openstack/"
        state: directory
    - name: "Generate admin password"
      set_fact:
        admin_pwd: "{{ lookup('password', 'build/admin_pwd', seed=inventory_hostname) }}"
    - name: "Create clouds.yaml for post-install configuration"
      vars:
        vm_address: "{{ hostvars['host']['vm_address'] }}"
      template:
        src: "clouds.yaml"
        dest: "~/.config/openstack/clouds.yaml"

- name: "Ubuntu install"
  hosts: guest
  become: yes
  vars:
    internal_lb_vip_address: "{{ hostvars['host']['vm_address'] }}"
    external_lb_vip_address: "{{ hostvars['host']['vm_address'] }}"
    keystone_memcached_servers: ""
    keystone_container_mysql_password: "{{ db_pwd }}"
    keystone_oslomsg_rpc_password: "{{ db_pwd }}"
    keystone_system_user_home: "/home/keystone"
    keystone_db_setup_host: guest
    keystone_oslomsg_rpc_setup_host: guest
    keystone_oslomsg_notify_setup_host: guest
    keystone_service_setup_host: guest
    oslomsg_rpc_policies: [ ]
    keystone_admin_user_name: admin
    keystone_auth_admin_password: "{{ admin_pwd }}"
    login_project_name: "admin"
    login_user_domain_name: "Default"
  roles:
    - openstack.config_template
    - name: os_keystone
      tags:
        - keystone-install
